# Generated by Django 4.1.4 on 2023-05-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blog_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='approx_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
